version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: app_start.sh
      timeout: 3600
      runas: root
